In [1]:

# from https://github.com/tensorflow/tensorflow/issues/25385
# more on https://youtu.be/-nTe44WT0ZI


import time
import numpy as np

import tensorflow as tf

print(tf.__version__)


layers = tf.keras.layers


2.0.0-alpha0


In [ ]:
import tensorflow_datasets as tfds
ds, info = tfds.load("mnist", as_supervised=True, with_info=True)
print(info)
train, test = ds["train"], ds["test"]


[5 0 4 ... 5 6 8]
[7, 6, 4, 8, 3, 8, 9, 0, 4, 1, 1, 2, 7, 4, 3, 0, 8, 7, 7, 7, 8, 0, 9, 1, 6, 2, 6, 9, 0, 9, 7, 0, 5, 6, 3, 9, 3, 7, 7, 3, 3, 5, 6, 4, 4, 7, 4, 6, 3, 2, 9, 4, 8, 1, 7, 7, 4, 3, 5, 4, 3, 6, 1, 1, 0, 7, 0, 9, 9, 7, 7, 0, 3, 0, 8, 3, 4, 9, 6, 1, 6, 9, 3, 1, 2, 9, 3, 1, 1, 6, 7, 5, 6, 2, 5, 3, 2, 9, 1, 8, 9, 8, 1, 3, 7, 3, 8, 9, 9, 5, 2, 7, 9, 6, 3, 4, 9, 0, 9, 0, 7, 1, 0, 3, 1, 4, 2, 2, 6, 7, 7, 0, 3, 2, 7, 6, 7, 2, 1, 5, 1, 9, 9, 3, 2, 3, 7, 9, 5, 5, 4, 4, 8, 9, 8, 4, 0, 9, 7, 0, 4, 9, 8, 5, 9, 1, 9, 7, 2, 7, 3, 0, 4, 2, 5, 3, 6, 9, 0, 3, 4, 6, 3, 4, 7, 2, 1, 5, 9, 2, 2, 7, 0, 4, 8, 7, 3, 6, 9, 1, 1, 9, 8, 5, 6, 4, 0, 3, 3, 0, 6, 7, 0, 8, 5, 4, 9, 5, 1, 3, 8, 6, 6, 6, 0, 2, 7, 3, 0, 4, 7, 9, 2, 4, 8, 7, 8, 1, 5, 6, 6, 3, 6, 8, 0, 1, 3, 7, 7, 7, 4, 7, 5, 5, 6, 6, 0, 8, 8, 6, 2, 9, 3, 2, 6, 3, 4, 7, 6, 6, 7, 2, 3, 2, 0, 6, 8, 1, 0, 6, 6, 7, 9, 5, 5, 8, 1, 3, 6, 4, 4, 2, 0, 6, 7, 9, 3, 8, 2, 1, 9, 5, 6, 5, 0, 5, 4, 9, 8, 5, 3, 5, 6, 6, 8, 3, 9, 4, 1, 1, 6, 2, 7, 5, 6, 2, 6, 

In [40]:

ex = tfds.as_numpy(train)
print(next(ex)[2].shape)

[5 0 4 ... 5 6 8]
[7, 6, 4, 8, 3, 8, 9, 0, 4, 1, 1, 2, 7, 4, 3, 0, 8, 7, 7, 7, 8, 0, 9, 1, 6, 2, 6, 9, 0, 9, 7, 0, 5, 6, 3, 9, 3, 7, 7, 3, 3, 5, 6, 4, 4, 7, 4, 6, 3, 2, 9, 4, 8, 1, 7, 7, 4, 3, 5, 4, 3, 6, 1, 1, 0, 7, 0, 9, 9, 7, 7, 0, 3, 0, 8, 3, 4, 9, 6, 1, 6, 9, 3, 1, 2, 9, 3, 1, 1, 6, 7, 5, 6, 2, 5, 3, 2, 9, 1, 8, 9, 8, 1, 3, 7, 3, 8, 9, 9, 5, 2, 7, 9, 6, 3, 4, 9, 0, 9, 0, 7, 1, 0, 3, 1, 4, 2, 2, 6, 7, 7, 0, 3, 2, 7, 6, 7, 2, 1, 5, 1, 9, 9, 3, 2, 3, 7, 9, 5, 5, 4, 4, 8, 9, 8, 4, 0, 9, 7, 0, 4, 9, 8, 5, 9, 1, 9, 7, 2, 7, 3, 0, 4, 2, 5, 3, 6, 9, 0, 3, 4, 6, 3, 4, 7, 2, 1, 5, 9, 2, 2, 7, 0, 4, 8, 7, 3, 6, 9, 1, 1, 9, 8, 5, 6, 4, 0, 3, 3, 0, 6, 7, 0, 8, 5, 4, 9, 5, 1, 3, 8, 6, 6, 6, 0, 2, 7, 3, 0, 4, 7, 9, 2, 4, 8, 7, 8, 1, 5, 6, 6, 3, 6, 8, 0, 1, 3, 7, 7, 7, 4, 7, 5, 5, 6, 6, 0, 8, 8, 6, 2, 9, 3, 2, 6, 3, 4, 7, 6, 6, 7, 2, 3, 2, 0, 6, 8, 1, 0, 6, 6, 7, 9, 5, 5, 8, 1, 3, 6, 4, 4, 2, 0, 6, 7, 9, 3, 8, 2, 1, 9, 5, 6, 5, 0, 5, 4, 9, 8, 5, 3, 5, 6, 6, 8, 3, 9, 4, 1, 1, 6, 2, 7, 5, 6, 2, 6, 

In [44]:
image = []
label = []
for example in tfds.as_numpy(train):
  image.append(example[0])
  label.append(example[1])



[5 0 4 ... 5 6 8]
[7, 6, 4, 8, 3, 8, 9, 0, 4, 1, 1, 2, 7, 4, 3, 0, 8, 7, 7, 7, 8, 0, 9, 1, 6, 2, 6, 9, 0, 9, 7, 0, 5, 6, 3, 9, 3, 7, 7, 3, 3, 5, 6, 4, 4, 7, 4, 6, 3, 2, 9, 4, 8, 1, 7, 7, 4, 3, 5, 4, 3, 6, 1, 1, 0, 7, 0, 9, 9, 7, 7, 0, 3, 0, 8, 3, 4, 9, 6, 1, 6, 9, 3, 1, 2, 9, 3, 1, 1, 6, 7, 5, 6, 2, 5, 3, 2, 9, 1, 8, 9, 8, 1, 3, 7, 3, 8, 9, 9, 5, 2, 7, 9, 6, 3, 4, 9, 0, 9, 0, 7, 1, 0, 3, 1, 4, 2, 2, 6, 7, 7, 0, 3, 2, 7, 6, 7, 2, 1, 5, 1, 9, 9, 3, 2, 3, 7, 9, 5, 5, 4, 4, 8, 9, 8, 4, 0, 9, 7, 0, 4, 9, 8, 5, 9, 1, 9, 7, 2, 7, 3, 0, 4, 2, 5, 3, 6, 9, 0, 3, 4, 6, 3, 4, 7, 2, 1, 5, 9, 2, 2, 7, 0, 4, 8, 7, 3, 6, 9, 1, 1, 9, 8, 5, 6, 4, 0, 3, 3, 0, 6, 7, 0, 8, 5, 4, 9, 5, 1, 3, 8, 6, 6, 6, 0, 2, 7, 3, 0, 4, 7, 9, 2, 4, 8, 7, 8, 1, 5, 6, 6, 3, 6, 8, 0, 1, 3, 7, 7, 7, 4, 7, 5, 5, 6, 6, 0, 8, 8, 6, 2, 9, 3, 2, 6, 3, 4, 7, 6, 6, 7, 2, 3, 2, 0, 6, 8, 1, 0, 6, 6, 7, 9, 5, 5, 8, 1, 3, 6, 4, 4, 2, 0, 6, 7, 9, 3, 8, 2, 1, 9, 5, 6, 5, 0, 5, 4, 9, 8, 5, 3, 5, 6, 6, 8, 3, 9, 4, 1, 1, 6, 2, 7, 5, 6, 2, 6, 

In [49]:
print(y_train)

print("================================================================")
print(label)
  
image_train, image_test = image_train / np.float32(255), image_test / np.float32(255)
label_train, label_test = y_train.astype(np.int64), y_test.astype(np.int64)

[5 0 4 ... 5 6 8]
[7, 6, 4, 8, 3, 8, 9, 0, 4, 1, 1, 2, 7, 4, 3, 0, 8, 7, 7, 7, 8, 0, 9, 1, 6, 2, 6, 9, 0, 9, 7, 0, 5, 6, 3, 9, 3, 7, 7, 3, 3, 5, 6, 4, 4, 7, 4, 6, 3, 2, 9, 4, 8, 1, 7, 7, 4, 3, 5, 4, 3, 6, 1, 1, 0, 7, 0, 9, 9, 7, 7, 0, 3, 0, 8, 3, 4, 9, 6, 1, 6, 9, 3, 1, 2, 9, 3, 1, 1, 6, 7, 5, 6, 2, 5, 3, 2, 9, 1, 8, 9, 8, 1, 3, 7, 3, 8, 9, 9, 5, 2, 7, 9, 6, 3, 4, 9, 0, 9, 0, 7, 1, 0, 3, 1, 4, 2, 2, 6, 7, 7, 0, 3, 2, 7, 6, 7, 2, 1, 5, 1, 9, 9, 3, 2, 3, 7, 9, 5, 5, 4, 4, 8, 9, 8, 4, 0, 9, 7, 0, 4, 9, 8, 5, 9, 1, 9, 7, 2, 7, 3, 0, 4, 2, 5, 3, 6, 9, 0, 3, 4, 6, 3, 4, 7, 2, 1, 5, 9, 2, 2, 7, 0, 4, 8, 7, 3, 6, 9, 1, 1, 9, 8, 5, 6, 4, 0, 3, 3, 0, 6, 7, 0, 8, 5, 4, 9, 5, 1, 3, 8, 6, 6, 6, 0, 2, 7, 3, 0, 4, 7, 9, 2, 4, 8, 7, 8, 1, 5, 6, 6, 3, 6, 8, 0, 1, 3, 7, 7, 7, 4, 7, 5, 5, 6, 6, 0, 8, 8, 6, 2, 9, 3, 2, 6, 3, 4, 7, 6, 6, 7, 2, 3, 2, 0, 6, 8, 1, 0, 6, 6, 7, 9, 5, 5, 8, 1, 3, 6, 4, 4, 2, 0, 6, 7, 9, 3, 8, 2, 1, 9, 5, 6, 5, 0, 5, 4, 9, 8, 5, 3, 5, 6, 6, 8, 3, 9, 4, 1, 1, 6, 2, 7, 5, 6, 2, 6, 

In [15]:

print(tfds.as_numpy(train))

[5 0 4 ... 5 6 8]
[7, 6, 4, 8, 3, 8, 9, 0, 4, 1, 1, 2, 7, 4, 3, 0, 8, 7, 7, 7, 8, 0, 9, 1, 6, 2, 6, 9, 0, 9, 7, 0, 5, 6, 3, 9, 3, 7, 7, 3, 3, 5, 6, 4, 4, 7, 4, 6, 3, 2, 9, 4, 8, 1, 7, 7, 4, 3, 5, 4, 3, 6, 1, 1, 0, 7, 0, 9, 9, 7, 7, 0, 3, 0, 8, 3, 4, 9, 6, 1, 6, 9, 3, 1, 2, 9, 3, 1, 1, 6, 7, 5, 6, 2, 5, 3, 2, 9, 1, 8, 9, 8, 1, 3, 7, 3, 8, 9, 9, 5, 2, 7, 9, 6, 3, 4, 9, 0, 9, 0, 7, 1, 0, 3, 1, 4, 2, 2, 6, 7, 7, 0, 3, 2, 7, 6, 7, 2, 1, 5, 1, 9, 9, 3, 2, 3, 7, 9, 5, 5, 4, 4, 8, 9, 8, 4, 0, 9, 7, 0, 4, 9, 8, 5, 9, 1, 9, 7, 2, 7, 3, 0, 4, 2, 5, 3, 6, 9, 0, 3, 4, 6, 3, 4, 7, 2, 1, 5, 9, 2, 2, 7, 0, 4, 8, 7, 3, 6, 9, 1, 1, 9, 8, 5, 6, 4, 0, 3, 3, 0, 6, 7, 0, 8, 5, 4, 9, 5, 1, 3, 8, 6, 6, 6, 0, 2, 7, 3, 0, 4, 7, 9, 2, 4, 8, 7, 8, 1, 5, 6, 6, 3, 6, 8, 0, 1, 3, 7, 7, 7, 4, 7, 5, 5, 6, 6, 0, 8, 8, 6, 2, 9, 3, 2, 6, 3, 4, 7, 6, 6, 7, 2, 3, 2, 0, 6, 8, 1, 0, 6, 6, 7, 9, 5, 5, 8, 1, 3, 6, 4, 4, 2, 0, 6, 7, 9, 3, 8, 2, 1, 9, 5, 6, 5, 0, 5, 4, 9, 8, 5, 3, 5, 6, 6, 8, 3, 9, 4, 1, 1, 6, 2, 7, 5, 6, 2, 6, 

In [ ]:
import tensorflow_datasets as tfds

# Set up datasets
def mnist_datasets():
  input_data = tfds.load("mnist", as_supervised=True)
  mnist_train, mnist_test = input_data["train"], input_data["test"]
  
    (x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()
    # Numpy defaults to dtype=float64; TF defaults to float32. Stick with float32.
    x_train, x_test = x_train / np.float32(255), x_test / np.float32(255)
    y_train, y_test = y_train.astype(np.int64), y_test.astype(np.int64)
    train_dataset = tf.data.Dataset.from_tensor_slices((x_train, y_train))
    test_dataset = tf.data.Dataset.from_tensor_slices((x_test, y_test))
    return train_dataset, test_dataset


In [ ]:
def create_model():
    max_pool = layers.MaxPooling2D((2, 2), (2, 2), padding='same')
    # The model consists of a sequential chain of layers, so tf.keras.Sequential
    # (a subclass of tf.keras.Model) makes for a compact description.
    return tf.keras.Sequential([
        layers.Reshape(
            target_shape=[28, 28, 1],
            input_shape=(28, 28,)),
        layers.Conv2D(2, 5, padding='same', activation=tf.nn.relu),
        max_pool,
        layers.Conv2D(4, 5, padding='same', activation=tf.nn.relu),
        max_pool,
        layers.Flatten(),
        layers.Dense(32, activation=tf.nn.relu),
        layers.Dropout(0.4),
        layers.Dense(10)])


# Define a loss function and accuracy function
def compute_loss(logits, labels):
    return tf.reduce_mean(tf.keras.losses.sparse_categorical_crossentropy(labels, logits))


def compute_accuracy(logits, labels):
    return tf.keras.metrics.categorical_accuracy(labels, logits)




In [ ]:

#@tf.function
#def square_if_positive_vectorized(x):
#  return tf.where(x > 0, x ** 2, x)


#square_if_positive_vectorized(tf.range(-5, 5))

#summary_writer = tf.summary.create_file_writer('/tmp/summaries')
#with summary_writer.as_default():
#  tf.summary.scalar('loss', 0.1, step=42)
  

In [ ]:
@tf.function
def train_step(model, optimizer, images, labels):
    # Record the operations used to compute the loss, so that the gradient
    # of the loss with respect to the variables can be computed.
    with tf.GradientTape() as tape:
        logits = model(images, training=True)
        loss = compute_loss(logits, labels)
        accuracy = compute_accuracy(logits, labels)
    grads = tape.gradient(loss, model.trainable_variables)
    optimizer.apply_gradients(zip(grads, model.trainable_variables))
    return loss, accuracy


In [ ]:
def train(model, optimizer, dataset, log_freq=10):

    """Trains model on `dataset` using `optimizer`."""
    start = time.time()
    # Metrics are stateful. They accumulate values and return a cumulative
    # result when you call .result(). Clear accumulated values with .reset_states()
    avg_loss = tf.keras.metrics.Mean('loss', dtype=tf.float32)
    avg_accuracy = tf.keras.metrics.Mean('accuracy', dtype=tf.float32)
    # Datasets can be iterated over like any other Python iterable.
    for images, labels in dataset:
        loss, accuracy = train_step(model, optimizer, images, labels)
        avg_loss.update_state(loss) #
        avg_loss(loss)
        avg_accuracy(accuracy)
        if tf.equal(optimizer.iterations % log_freq, 0):
            tf.summary.scalar('loss', avg_loss.result(), step=optimizer.iterations)
            tf.summary.scalar('accuracy', avg_accuracy.result(), step=optimizer.iterations)
            avg_loss.reset_states()
            avg_accuracy.reset_states()
            rate = log_freq / (time.time() - start)
            print('Step #%d\tLoss: %.6f (%d steps/sec)' % (optimizer.iterations, loss, rate))
            start = time.time()


def test(model, dataset, step_num):
    """Perform an evaluation of `model` on the examples from `dataset`."""
    avg_loss = tf.keras.metrics.Mean('loss', dtype=tf.float32)
    avg_accuracy = tf.keras.metrics.Mean('accuracy', dtype=tf.float32)

    for (images, labels) in dataset:
        logits = model(images, training=False)
        avg_loss(compute_loss(logits, labels))
        avg_accuracy(compute_accuracy(logits, labels))
    print('Model test set loss: {:0.4f} accuracy: {:0.2f}%'.format(
        avg_loss.result(), avg_accuracy.result() * 100))
    tf.summary.scalar('loss', avg_loss.result(), step=step_num)
    tf.summary.scalar('accuracy', avg_accuracy.result(), step=step_num)


In [ ]:

model = create_model()

optimizer = tf.keras.optimizers.SGD(learning_rate=0.01, momentum=0.5)

train_ds, test_ds = mnist_datasets()
train_ds = train_ds.shuffle(60000).batch(100)
test_ds = test_ds.batch(100)

train_summary_writer = tf.summary.create_file_writer('/tmp/summaries/train')
test_summary_writer = tf.summary.create_file_writer('/tmp/summaries/test')

for epoch in range(10):
  start = time.time()
  with train_summary_writer.as_default():
    train(model, optimizer, train_ds)
  end = time.time()
  print('\nTrain time for epoch #{} ({} total steps): {}'.format(epoch + 1, optimizer.iterations, end - start))
  with test_summary_writer.as_default():
    test(model, test_ds, optimizer.iterations)